# Generated by Django 3.2.9 on 2021-11-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('dimage', models.CharField(max_length=50)),
                ('dplace', models.CharField(max_length=50)),
                ('dpin', models.CharField(max_length=50)),
                ('dpost', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('DEPID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.dept')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('uimage', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('uplace', models.CharField(max_length=50)),
                ('upost', models.CharField(max_length=50)),
                ('udistrict', models.CharField(max_length=50)),
                ('upin', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.login')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('simage', models.CharField(max_length=50)),
                ('splace', models.CharField(max_length=50)),
                ('spin', models.CharField(max_length=50)),
                ('spost', models.CharField(max_length=50)),
                ('xperience', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('DEPID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.dept')),
                ('LOGIN', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.login')),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('fromtime', models.CharField(max_length=50)),
                ('totime', models.CharField(max_length=50)),
                ('added_date', models.CharField(max_length=50)),
                ('DOCID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='leavereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_need_date', models.CharField(max_length=50)),
                ('request_date', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=50)),
                ('STAFFID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.staff')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='LOGIN',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.login'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('SCHDID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.CharField(max_length=50)),
                ('checkout_time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('STAFFID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospial.staff')),
            ],
        ),
    ]
