# Generated by Django 3.2.9 on 2021-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0002_staff_sgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='dgender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
