# Generated by Django 3.2.9 on 2022-01-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0003_doctor_dgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.DateField(max_length=50),
        ),
    ]
