# Generated by Django 3.2.9 on 2022-01-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0004_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=50),
        ),
    ]
