# Generated by Django 3.2.9 on 2022-02-15 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0007_user_ugender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospial.user'),
        ),
    ]
