# Generated by Django 3.2.9 on 2022-02-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0008_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.IntegerField(),
        ),
    ]
