# Generated by Django 3.2.9 on 2022-02-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0009_alter_booking_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='token',
            field=models.IntegerField(default=1),
        ),
    ]
