# Generated by Django 3.2.9 on 2022-02-17 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0010_alter_booking_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereq',
            name='request_date',
        ),
    ]
