# Generated by Django 3.2.9 on 2022-02-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0011_remove_leavereq_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorleav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fro_m', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
            ],
        ),
    ]
