# Generated by Django 3.2.9 on 2022-02-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0012_doctorleav'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleav',
            name='DOCID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospial.doctor'),
        ),
        migrations.AddField(
            model_name='doctorleav',
            name='des',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='doctorleav',
            name='reqdate',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorleav',
            name='fro_m',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorleav',
            name='to',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
