# Generated by Django 3.2.9 on 2022-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospial', '0013_auto_20220218_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereq',
            name='request_date',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='leavereq',
            name='to',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavereq',
            name='des',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavereq',
            name='leave_need_date',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
